version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_app_ts_advanced
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data:
